Productividad/urls.py
from django.urls import path
from .views import VistaInicio, VistaCrear, actualizar_tiempos, completar, obtener_tiempos, VistaActualizar, EliminarTarea
app_name = 'Productividad'

urlpatterns = [
    path('', VistaInicio.as_view(), name='indice'),
    path('crear/', VistaCrear.as_view(), name='crear'),
    path('actualizar/<int:pk>', VistaActualizar.as_view(), name='actualizar'),
    path('ajax/actualizar/', actualizar_tiempos, name='actualizar_t'),
    path('ajax/completar/', completar, name='completar_t'),
    path('ajax/obtener_tiempos/', obtener_tiempos, name='obtener_t'),
    path('eliminar_tarea/<int:pk>', EliminarTarea.as_view(), name='eliminar_t'),
]

TestAbraxas/urls.py
from django.contrib import admin
from django.urls import path, include
from Productividad.views import VistaInicio1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', VistaInicio1.as_view(), name='inicio1'),
    path('productividad/', include('Productividad.urls', namespace='Productividad')),
]

Productividad/models.py
from django.db import models

class Tarea(models.Model):
    nombre = models.CharField(max_length=32)
    descripcion = models.TextField(max_length=256)
    completado = models.BooleanField(default=False)

    h_inicio = models.PositiveIntegerField(null=True, default=0, blank=True)
    m_inicio = models.PositiveIntegerField(null=True, default=0, blank=True)
    s_inicio = models.PositiveIntegerField(null=True, default=0, blank=True)

    h_actual = models.PositiveIntegerField(null=True, default=0, blank=True)
    m_actual = models.PositiveIntegerField(null=True, default=0, blank=True)
    s_actual = models.PositiveIntegerField(null=True, default=0, blank=True)

    def completar(self):
        self.completado = True

    # def save(self, *args, **kwargs):
    #     self.h_actual = self.h_inicio
    #     self.m_actual = self.m_inicio
    #     self.s_actual = self.s_inicio
    #     super(Tarea, self).save(*args, **kwargs)

    def __str__(self):
        return '{}, {} completado'.format(self.nombre, 'si' if self.completado else 'no')

Productividad/forms.py
from django import forms
from .models import Tarea

class FormTarea(forms.ModelForm):
    class Meta():
        model = Tarea
        fields = ('nombre', 'descripcion', 'h_inicio', 'm_inicio', 's_inicio')
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'input-nombre'}),
            'descripcion': forms.Textarea(attrs={'class': 'input-descripcion'}),
            'h_inicio': forms.NumberInput(attrs={'min': '0', 'max': '1'}),
            'm_inicio': forms.NumberInput(attrs={'min': '0', 'max': '60'}),
            's_inicio': forms.NumberInput(attrs={'min': '0', 'max': '60'}),
        }
        labels = {
            'h_inicio': 'Horas',
            'm_inicio': 'Minutos',
            's_inicio': 'Segudos',
        }

Productividad/views.py
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView
from django.views.generic.edit import FormView
from django.urls import reverse
from .forms import FormTarea
from .models import Tarea

class VistaInicio1(TemplateView):
    template_name = 'inicio.html'

class VistaInicio(ListView):
    template_name = 'Productividad/index.html'
    model = Tarea
    context_object_name = 'tareas'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'ids' in self.request.session:
            ids = self.request.session['ids']
        else:
            ids = list()
            self.request.session['ids'] = ids
        context['tareas'] = Tarea.objects.filter(id__in=ids)
        return context
class VistaCrear(CreateView):
    template_name = 'Productividad/crear.html'
    form_class = FormTarea
    # fields = ('nombre', 'descripcion', 'h_inicio', 'm_inicio', 's_inicio')
    # widgets = {
    #     'nombre': forms.TextInput(attrs={'class': 'input-nombre'}),
    #     'descripcion': forms.Textarea(attrs={'class': 'input-descripcion'}),
    #     'h_inicio': forms.NumberInput(attrs={'min': '0', 'max': '1'}),
    #     'm_inicio': forms.NumberInput(attrs={'min': '0', 'max': '60'}),
    #     's_inicio': forms.NumberInput(attrs={'min': '0', 'max': ''}),
    #     }
    def form_valid(self, form):
        self.object = form.save()
        self.object.h_actual = self.object.h_inicio
        self.object.m_actual = self.object.m_inicio
        self.object.s_actual = self.object.s_inicio
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        if 'ids' in self.request.session:
            ids = self.request.session['ids']
        else:
            ids = list()
            self.request.session['ids'] = ids
        ids.append(self.object.pk)
        self.request.session['ids'] = ids
        return reverse('Productividad:indice')

class VistaActualizar(UpdateView):
    model = Tarea
    fields = ['nombre', 'descripcion', 'h_inicio', 'm_inicio', 's_inicio']
    template_name_suffix = '_update_form'
    def get_success_url(self):
        return reverse('Productividad:indice')
class EliminarTarea(DeleteView):
    model = Tarea
    context_object_name = 'tarea'
    form_class = FormTarea

    def get_success_url(self):
        if 'ids' in self.request.session:
            ids = self.request.session['ids']
        else:
            ids = list()
            self.request.session['ids'] = ids
        ids.remove(self.object.pk)
        self.request.session['ids'] = ids
        return reverse('Productividad:indice')

def actualizar_tiempos(request):
    id_tarea = request.GET.get('pk', None)
    tiempos = request.GET.getlist('tiempos[]', None)
    tarea = Tarea.objects.filter(pk=id_tarea)[0]
    if not tarea.completado:
        print(id_tarea, tiempos)
        tarea.h_actual = int(tiempos[0])
        tarea.m_actual = int(tiempos[1])
        tarea.s_actual = int(tiempos[2])
        #update_fields=['h_actual', 'm_actual', 's_actual']
        if tiempos[0] == '0' and tiempos[1] == '0' and tiempos[2] == '0':
            tarea.completado = True
            print('tarea completada')
        tarea.save()
        print(tarea)
    data = {
        'exito': True,
    }
    return JsonResponse(data)

def completar(request):
    id_tarea = request.GET.get('pk', None)
    tarea = Tarea.objects.filter(pk=id_tarea)[0]
    if not tarea.completado:
        tarea.completado = True

        print('tarea completada')
        tarea.save()
        print(tarea)
    data = {
        'exito': True,
    }
    return JsonResponse(data)

def obtener_tiempos(request):
    id_tarea = request.GET.get('pk', None)
    tarea = Tarea.objects.filter(pk=id_tarea)[0]
    data = {
        'tiempos': [tarea.h_inicio, tarea.m_inicio, tarea.s_inicio],
    }
    return JsonResponse(data)

def eliminar_tarea(request):
    id_tarea = request.GET.get('pk', None)
    # tarea = Tarea.objects.filter(pk=id_tarea)[0]
    print(request.session['ids'])
    request.session['ids'].remove(int(id_tarea))
    print('tarea eliminada')
    data = {
        'exito': True,
    }
    return JsonResponse(data)

templates/Productividad/crear.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block titulo %}
<title>Crear nueva tarea</title>
{% endblock titulo %}

{% block contenido %}
<div class="jumbotron">
    <h1 class="display-4">Crear Tarea</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-primary" type="submit" value="Crear">
    </form>
</div>
{% endblock contenido %}

templates/Productividad/index.html
{% extends 'base.html' %}

{% block titulo %}
<title>Inicio</title>
{% endblock titulo %}

{% block contenido %}
<!-- <div data-countdown="+1h +10m +5s"></div>
<div data-countdown="+0h +30m +30s"></div> -->
{% if tareas %}
    <div class="jumbotron">
        <h1 class="display-4">Tareas activas:</h1>
        {% for tarea in tareas %}   
        {% if not tarea.completado %}
        <div class="btn-group" role="group" aria-label="Basic example">
            <a type="button" class="btn btn-info" href="{% url 'Productividad:actualizar' pk=tarea.pk %}">{{ tarea }}</a>
            <button type="button" id="completar" alt="{{ tarea.pk }}" class="btn btn-primary">Completar</button>
            <button type="button" id="pausa" alt="{{ tarea.pk }}" class="btn btn-secondary">Pausar</button>
            <button type="button" id="reiniciar" alt="{{ tarea.pk }}" class="btn btn-warning">Reiniciar</button>
            <a href="{% url 'Productividad:eliminar_t' pk=tarea.pk %}" type="button" class="btn btn-danger">Eliminar</a>
        </div>
        <div class="card-body">
            <p class="card-text">{{ tarea.descripcion }}</p>
        </div>
        <div class="tiempo" id="{{ tarea.pk }}" data-countdown="+{{ tarea.h_actual }}h +{{ tarea.m_actual }}m +{{ tarea.s_actual }}s"></div>
        {% endif %}
        {% endfor %}
    </div>
    <div class="jumbotron">
        <h1 class="display-4">Tareas completadas:</h1>
        {% for tarea in tareas %}
        {% if tarea.completado %}
        <div class="btn-group" role="group" aria-label="Acciones">
            <button type="button" class="btn btn-info">{{ tarea }}</button>
            <a href="{% url 'Productividad:eliminar_t' pk=tarea.pk %}" type="button" class="btn btn-danger">Eliminar</a>
        </div>
        <div class="card-body">
            <p class="card-text">{{ tarea.descripcion }}</p>
        </div>
        <div class="completado" id="{{ tarea.pk }}" data-countdown="+{{ tarea.h_actual }}h +{{ tarea.m_actual }}m +{{ tarea.s_actual }}s"></div>
        {% endif %}
        {% endfor %}
    </div>
    <script type="text/javascript">
        $('[data-countdown]').each(function() {
            var $this = $(this), finalDate = $(this).data('countdown');
            $this.countdown({
                until: finalDate,
                onTick: minuto,
                tickInterval: 10,
            });
        });
        $('.btn-group').each(function() {
            var $this = $(this);
            $this.find('#pausa').click(function() {
                var pause = $(this).text() === 'Pausar'; 
                $(this).text(pause ? 'Continuar' : 'Pausar');
                $('div#' + $(this).attr('alt')).countdown(pause ? 'pause' : 'resume'); 
            });
            $this.find('#completar').click(function() {
                id = $(this).attr('alt');
                $.ajax({
                    url: "{% url 'Productividad:completar_t' %}",
                    data: {
                        'pk': id,
                    },
                    dataType: 'json',
                    success: function(data) {
                        location.reload();
                    }
                });
                $('div#' + id).countdown('pause');
            });
            $this.find('#reiniciar').click(function() {
                id = $(this).attr('alt');
                $.ajax({
                    url: "{% url 'Productividad:obtener_t' %}",
                    data: {
                        'pk': id,
                    },
                    dataType: 'json',
                    success: function(data) {
                        var finalDate = "+" + data.tiempos[0] + "h +" + data.tiempos[1] + "m +" + data.tiempos[2] + "s";
                        console.log(finalDate);
                        $('div#' + id).countdown('destroy');
                        $('div#' + id).countdown({
                            until: finalDate,
                            onTick: minuto,
                            tickInterval: 10,
                        });
                    }
                });
            });
        });
        $('.completado').countdown('pause');
        function minuto() {
            try {
                console.log('paso un minuto.');
                let $tiempos = $('.tiempo');
                for(tiempo of $tiempos) {
                    pk = tiempo.id
                    t = tiempo.getElementsByClassName('countdown-section');
                    var t1 = [t[0].textContent.match(/\d+/g).map(Number)[0], t[1].textContent.match(/\d+/g).map(Number)[0], t[2].textContent.match(/\d+/g).map(Number)[0]];
                    $.ajax({
                        url: "{% url 'Productividad:actualizar_t' %}",
                        data: {
                            'pk': pk,
                            'tiempos[]': t1,
                        },
                        dataType: 'json',
                    });
                }
            }
            catch(err) {}
        } 
         
        /*let $tiempos = $('.tiempo');
        for(tiempo of $tiempos) {
            t = tiempo.find('countdown-section');
            for(let el of t) {
                console.log(el.textContent, tiempo.id);
            }
        }*/
        
    </script>
{% else %}
<div class="jumbotron">
    <h1 class="display-4">No hay tareas por el momento, <br> ¡Crea una!</h1>
</div>
{% endif %}
{% endblock contenido %}

templates/Productividad/tarea_confirm_delete.html
{% extends 'base.html' %}

{% block titulo %}
<title>Eliminar tarea</title>
{% endblock titulo %}

{% block contenido %}
<div class="jumbotron">
    <form method="post">{% csrf_token %}
        <h1 class="display-4">Seguro que quieres eliminar "{{ tarea.nombre }}"?</h1>
        <input class="btn btn-primary"  type="submit" value="Confirmar">
    </form>
</div>

{% endblock contenido %}

templates/Productividad/tarea_update_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block titulo %}
<title>Modificar tarea</title>
{% endblock titulo %}

{% block contenido %}
<div class="jumbotron">
    <h1 class="display-4">Actualizar Tarea</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-primary" type="submit" value="Actualizar">
    </form>
</div>
{% endblock contenido %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    {% block titulo %}
    {% endblock titulo %}
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.plugin.js' %}"></script>
    <script src="{% static 'js/jquery.countdown.js' %}"></script>
    <script src="{% static 'js/jquery.countdown-es.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.countdown.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark">
            <a class="navbar-brand" href="{% url 'Productividad:indice' %}">App de Productividad</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'Productividad:indice' %}">Inicio <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'Productividad:crear' %}">Crear tarea <span class="sr-only">(current)</span></a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <main class="container ">
        <section class="fill">
            {% block contenido %}
            {% endblock contenido %}
        </section>
    </main>
    <footer>

    </footer>
</body>

</html>

templates/inicio.html
{% extends 'base.html' %}

{% block titulo %}
<title>Inicio</title>
{% endblock titulo %}

{% block contenido %}
<div class="jumbotron">
    <h1 class="display-4">Aplicación de productividad</h1>
    <p class="lead">Para acceder a ella, haz click en el siguiente botón.</p>
    <a href="{% url 'Productividad:indice' %}" type="button" class="btn btn-primary">Acceder</a>
</div>
{% endblock contenido %}